services:
  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: nacos
    environment:
      - MODE=standalone
      - NACOS_AUTH_ENABLE=false   # 关闭认证以避免 NACOS_AUTH_IDENTITY_KEY 报错
    ports:
      - "8848:8848"
    volumes:
      - ./nacos_data:/home/nacos/data


  demo-app:
    build: ./demo-app
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
